### PR TITLE
Swag 2k16

### PR DESCRIPTION
**Pull request by RandomToon**

### CODE REVIEW

**Comment by Grant11** [comment]
You are gay

**Comment by MrExternal** [comment]
You aren't funny, kindly take yourself and leave this repository.

**Comment by NickdogeGaming** [comment]
kill yourself skid, please.

**Comment by MrExternal** [comment]
Ay there ya go Nick. 

Also, seriously. *RandomToon*

Do not fork the repository, and especially don't use it for making a server.

**Comment by RandomToon** [comment]
That's why I removed the Pull Request.
Stealing TTR Source is fun, so I'll leave it to you and to ruin TTP.

**Comment by RandomToon** [comment]
Says the one ruining Servers,

**Comment by MrExternal** [comment]
We might've taken the source code from 2014, but we are *not* afraid to admit it. 

We needed a base to start with, so we've chosen Rewritten's old source and now we are gradually removing their code. There is *also* no issue because we are willing to give credit to Rewritten for their work. 

Oh, and Nick ruins *skid* servers. 
Planet is one of them, corrupted and full of liars.

**Comment by RandomToon** [comment]
Also, Skid isn't a Insult. Heterosexual Faggot.

**Comment by MrExternal** [comment]
Skid is an insult. 

Also, nice job calling us out on sexuality when we're all straight here.. Lmao

**Comment by RandomToon** [comment]
Also I am not a skid, i fixed the CEO Crash and Mailbox Crash on
ToontownStrideOfficial Github.

**Comment by MrExternal** [comment]
Congrats, want a cookie? 

Hmu on Skype buddy, you obviously seem confident here.

**Comment by RandomToon** [comment]
Naw, all your commits pretty much have (Mature) Content. Get Mature PLS.

**Comment by MrExternal** [comment]
We do what we want, not like we're an official server lmao. 

It's the internet, remember if you can't handle it to click the "X" button.

**Comment by RandomToon** [comment]
The repo will be removed in the Morning! Have a Great Day!

**Comment by MrExternal** [comment]
Eh, we can remake it lmao. 

We have everything backed up, and I don't mind clicking a few buttons.

**Comment by RandomToon** [comment]
No I meant my repo. LOL.

**Comment by MrExternal** [comment]
Should've been more specific.

**Comment by RandomToon** [comment]
Why would I remove your work?

**Comment by NickdogeGaming** [comment]
Hey faggot randomautist hmu on skype (or mr external)

**Comment by MrExternal** [comment]
You definitely seemed like you had an intention, Panda.

**Comment by RandomToon** [comment]
Good Night, I am not dumb enough to give my Skype to you. So you can use a Skype Resolver to DDOS my Ass. No Thank You.

**Comment by NickdogeGaming** [comment]
you're a pussy? btw ddosing is for harmless faggots lmao

**Comment by MrExternal** [comment]
I'll leave this here. 

Since it is clearly obvious you attempted to steal our work and claim it as your own, I am going to point out each and every flaw you have committed here. 

1: *You forget, as the owner I can see when people fork my repo.* 
You obviously didn't account for the fact I can see when people fork my repository, and when they do it is an *assured* check on their profile to see if they use the source for purposes we do not want, such as making a *server.* 

2: *We are not the people you wanna try and steal from.* 
You know Nick, the guy who can make your life a nightmare. Then you have the rest of us here, who do *not* take lightly when you use our work and then have the *fucking nerve* to change the README and other shit to conceal your little plan. 

3: *You lack the ability to read the README before doing anything.* 
The README, which I spent quite a bit of time on, *specifies* what you can do with this repository. Instead, you decide *"Oh, I'm gonna use this for a server!* when the README specifically says.. *DO NOT MAKE A SERVER* 

4: *You have the balls to tell us to mature on our on repository.*
We can say and do *whatever* we want here, since we are NOT caring about reputation or incessant bullshit like that. So what if our commits have "mature" content? Doesn't mean we can't use swear words. 

Finally, *you have messed up.* 
We do *not* take this lightly, as I've said. You've already begun to feel scared, I know it. 
Simply remove your repository, and nothing more will come of this. However, that can change if you keep the repository up and attempt to recreate a server with this source code.

**Comment by Grant11** [comment]
Fuck

**Pull request closed without merging**
